
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihwcnwgxhzpthbisqkap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod2Nud2d4aHpwdGhiaXNxa2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDA3MjYsImV4cCI6MjA2MzExNjcyNn0.3CyAQ25q9jGwsGVJBR6bNGbrcjvnR05xJdkMtBZuevQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
